version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://postgres:password@edugators:5433/postgres
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: edugators-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: edugators
    ports:
      - "5433:5432"
    volumes:
      - ./src/backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  pgdata:
