version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: edugator-server
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      edugators-db:
        condition: service_healthy

  edugators-db:
    image: postgres:13
    container_name: edugators-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./src/backend/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 20s
      retries: 5
